### ISSUE TITLE
Organisation Challenge Actuaires Data Visualisation

### ISSUE THREAD

**Issue by natR** [natR/Challenge-Data-Viz-2021#1]
### **Points d'organisation du Challenge**

Projet accepté par le Conseil de l'Institut des Actuaires le 16 mars 2021. Budget de 10K€ accordé pour l'événement.

- [x] Rédiger le pitch d'ici fin avril https://github.com/natR/Challenge-Data-Viz-2021/issues/3
- [ ] Rédiger le formulaire d'inscription ? 
- [ ] Questionnaires et inscriptions (préciser que le nombre d'inscription est limité)
- [ ]  Réglement du concours
     - [x]  Samuel envoi une première monture fin avril https://github.com/natR/Challenge-Data-Viz-2021/issues/1#issuecomment-848582381
- [ ] Date : du 1er octobre (17h ?) au 17 octobre 2021 (minuit)
- [ ] Participants : M2 filières d'actuariat + DSA 
- [ ] Données Covid : Il existe déjà des visuels très "poussés" que peuvent apporter de plus les candidats ?  ==> voir avec Jean-Claude https://github.com/natR/Challenge-Data-Viz-2021/issues/2
- [ ] Outils : R ou Python
- [ ] Deux conférences : 
        1. une en amont avec un expert en visualisation vers la mi-septembre : webinar organisé par l'IA tous les actuaires et les participants sont invités ==> voir avec Samuel
        2. un webinar organisationnel uniquement avec les participants ==> voir avec Samuel
- [ ] Composition du jury : Qui se propose pour être membre du jury ?
- [ ] Etablir une grille avec 5 critères max
- [ ] Restitution : 
       1. Vidéo de 3 minutes à délivrer au jury en amont du passage des candidats.
       2. Présentation pptx 3 ou 4 slides max
       2. Passage des candidats : speech d'1 mn chacun pour présenter l'approche choisie
- [ ] Prix : A déterminer
- [ ] Stockage des données ==> Dropbox voir avec Samuel
- [ ] Communication été 2021 aux filières actuariat

**Comment by natR** [comment]
### **Membres Club Algo pour la constitution du jury**

- [ ] Membres : 

1. XXX
2. xxx

- [ ] Suppléants : 

1. David
2. Victor
3.

**Comment by moilerat** [comment]
~@natR : je ne peux pas éditer le corps du ticket, ce qui me semblerait mieux pour intégrer les différentes remarques.
Ton repo est ouvert mais cela ne permet pas de modifier~

Les commentaires de Florence Picard : 

- concernant les données, je me demande si nous ne pourrions pas axer sur la surmortalité en période Covid, et mettre des données de mortalité toutes causes, françaises, européennes.
Il y aurait un peu plus d’ "actuariat » et il y a eu moins de visualisation.

- concernant le webinaire ouvert, peut-être avez-vous une idée, Intervenant : 
 Charles Miglietti (Toucan Toco). https://toucantoco.com/blog/charles-miglietti-portrait-startup/ 
Je l’avais fait intervenir au début du GT Big Data (en 2014 je crois).Il est très bon.

- concernant la grille, j’attire l’attention sur un point qui me semble important pour notre profession d’actuaire: que la data visualisation soit utilisée pour 
- mettre en valeur nos résultats (pas un outil avec lequel on peut cliquer partout pour avoir des détails et "faire son marché", sans fournir des résultats d’aide à la décision.) rq de VR : illustrer des modèles ou donner lieu a des interprétations

- concernant le jury, < 6 ou 7, représentation des deux dimensions actuariat et visualisation

**Comment by JeanClaudeR** [comment]
@natR dans Github, tu peux créer une "Organisation", associée à ton compte par exemple.
Par ailleurs, il vaudrait mieux avoir plusieurs issues selon les sujets à traiter. Plus facile pour assigner aussi un responsable du/des sujets.

**Comment by moilerat** [comment]
Version du règlement en date du 27-04

[Réglement Concours Club Algo.docx](https://github.com/natR/Challenge-Data-Viz-2021/files/6545128/Reglement.Concours.Club.Algo.docx)
